### ISSUE TITLE
windows mvc is showing blank page.

### ISSUE THREAD

**Issue by sridkdhar** [cliftonc/express-mvc-bootstrap#14]
Hi,

I am new to node and mvc. I tried to install node windows version and used ryppi to install all the dependencies now I could able to run all express and its examples correctly. Now how to run eb command on windows command prompt? I could not find equivalent command for eb in windows XP How run this file. Please help.  I like the structure and even 404 and 500 links are working correctly. Please give a solution for windows too.

regards
Sridhar DK

**Comment by cliftonc** [comment]
Sridhar,

I would assume that 'node bin/eb' would work?  The eb script is just a node file, but it is prefixed with a bash flag to indicate to linux / macosx that it should be executed by node.

Apologies as I don't actually use a windows PC, and hence if you want it to work better in Windows it would be great if you could fork it, fix it, and submit a pull request - I really can't do much but offer advice.

Cheers,
Clifton

**Comment by sridkdhar** [comment]
Thank you Clifton,

I am getting the following error when executing  "node bin/eb"

But when i run node app.js it is server is running. I am suspecting some
paths are missing in my env.

-- my screen
E:\Node\myapp>node eb

node.js:207
        throw e; // process.nextTick error, or 'error' event on first tick
              ^
Error: require.paths is removed. Use node_modules folders, or the NODE_PATH
envi
ronment variable instead.
    at Function.<anonymous> (module.js:376:11)
    at Object.<anonymous> (E:\Node\myapp\eb:19:8)
    at Module._compile (module.js:432:26)
    at Object..js (module.js:450:10)
    at Module.load (module.js:351:31)
    at Function._load (module.js:310:12)
    at Array.<anonymous> (module.js:470:10)
    at EventEmitter._tickCallback (node.js:199:26)

E:\Node\myapp>node app.js
Express server 2.5.0 listening on port 3000

With warm regards
Sridhar dk
+91-949 045 7590

On Wed, Nov 16, 2011 at 7:09 PM, Clifton Cunningham <
reply@reply.github.com

> wrote:
> 
> Sridhar,
> 
> I would assume that 'node bin/eb' would work?  The eb script is just a
> node file, but it is prefixed with a bash flag to indicate to linux /
> macosx that it should be executed by node.
> 
> Apologies as I don't actually use a windows PC, and hence if you want it
> to work better in Windows it would be great if you could fork it, fix it,
> and submit a pull request - I really can't do much but offer advice.
> 
> Cheers,
> Clifton
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> 
> https://github.com/cliftonc/express-mvc-bootstrap/issues/14#issuecomment-2759439

## 

With best regards
Sridhar dk
+91-9490457590

**Comment by cliftonc** [comment]
Ahh - you are using node 0.5.0, it won't work in 0.5.0 unless we refactor
the entire project to not rely on require.paths.  This has been done in
Calipso, it requires some additional work in each module to allow the
rootpath of the application to be set and used.

This needs work - which I am unable to do at the moment, but happy for you
to have a go at it - take a look at Calipso for ideas.

Clifton

On 16 November 2011 13:59, Sridhar <
reply@reply.github.com

**Comment by sridkdhar** [comment]
Dear Clifton,

I have 0.5.0 only available for windows platform. So let me wait till
nodejs updated.

With warm regards
Sridhar dk

On Wed, Nov 16, 2011 at 7:31 PM, Clifton Cunningham <
reply@reply.github.com

> wrote:
> 
> Ahh - you are using node 0.5.0, it won't work in 0.5.0 unless we refactor
> the entire project to not rely on require.paths.  This has been done in
> Calipso, it requires some additional work in each module to allow the
> rootpath of the application to be set and used.
> 
> This needs work - which I am unable to do at the moment, but happy for you
> to have a go at it - take a look at Calipso for ideas.
> 
> Clifton
> 
> On 16 November 2011 13:59, Sridhar <
> reply@reply.github.com
> 
> > wrote:
> > 
> > Thank you Clifton,
> > 
> > I am getting the following error when executing  "node bin/eb"
> > 
> > But when i run node app.js it is server is running. I am suspecting some
> > paths are missing in my env.
> > 
> > -- my screen
> > E:\Node\myapp>node eb
> > 
> > node.js:207
> >        throw e; // process.nextTick error, or 'error' event on first tick
> >              ^
> > Error: require.paths is removed. Use node_modules folders, or the
> > NODE_PATH
> > envi
> > ronment variable instead.
> >    at Function.<anonymous> (module.js:376:11)
> >    at Object.<anonymous> (E:\Node\myapp\eb:19:8)
> >    at Module._compile (module.js:432:26)
> >    at Object..js (module.js:450:10)
> >    at Module.load (module.js:351:31)
> >    at Function._load (module.js:310:12)
> >    at Array.<anonymous> (module.js:470:10)
> >    at EventEmitter._tickCallback (node.js:199:26)
> > 
> > E:\Node\myapp>node app.js
> > Express server 2.5.0 listening on port 3000
> > 
> > With warm regards
> > Sridhar dk
> > +91-949 045 7590
> > 
> > On Wed, Nov 16, 2011 at 7:09 PM, Clifton Cunningham <
> > reply@reply.github.com
> > 
> > > wrote:
> > > 
> > > Sridhar,
> > > 
> > > I would assume that 'node bin/eb' would work?  The eb script is just a
> > > node file, but it is prefixed with a bash flag to indicate to linux /
> > > macosx that it should be executed by node.
> > > 
> > > Apologies as I don't actually use a windows PC, and hence if you want
> > > it
> > > to work better in Windows it would be great if you could fork it, fix
> > > it,
> > > and submit a pull request - I really can't do much but offer advice.
> > > 
> > > Cheers,
> > > Clifton
> > > 
> > > ---
> > > 
> > > Reply to this email directly or view it on GitHub:
> > 
> > https://github.com/cliftonc/express-mvc-bootstrap/issues/14#issuecomment-2759439
> > 
> > 
> > ## 
> > 
> > With best regards
> > Sridhar dk
> > +91-9490457590
> > 
> > ---
> > 
> > Reply to this email directly or view it on GitHub:
> > 
> > https://github.com/cliftonc/express-mvc-bootstrap/issues/14#issuecomment-2759643
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> 
> https://github.com/cliftonc/express-mvc-bootstrap/issues/14#issuecomment-2759651

## 

With best regards
Sridhar dk
+91-9490457590
